name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9

    steps:

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: crtm
        submodules: true

    - name: build
      run: |
        cd crtm
        mkdir build
        cd build
        cmake ..
        make -j2
